spring:
  application:
    name: traces-tutorial

management:
  tracing:
    sampling:
      probability: 1.0

otel:
  exporter:
    otlp:
      endpoint: "http://localhost:4318"
  traces:
    exporter: otlp
  metrics:
    exporter: none
  logs:
    exporter: none

logging:
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}] '
